[variables]
NODE_VERSION = "20.19.0"

[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "cd api && npm install --production=false"
]

[phases.build]
cmds = [
  "cd api && npm run build"
]

[start]
cmd = "cd api && npm start"